include:
  - board: seeeduino_xiao_ble
    shield: totem_dongle
    snippet: studio-rpc-usb-uart
    # snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: totem_left
    # remove to disable dongle (maybe also settings_reset)
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: seeeduino_xiao_ble
    shield: totem_right
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
